service: device
show-fields:
  - model
  - version
  - vendor
  - architecture
  - status
  - address
  - bootupTimestamp
apply:
  eos:
    version: all
    command: show version
    normalize: '[
    "modelName: model",
    "version: version",
    "vendor: vendor?|Arista",
    "os: os?|EOS",
    "architecture: architecture",
    "bootupTimestamp: bootupTimestamp"]'

  cumulus:
    version: all
    command: cat /proc/uptime; hostnamectl
    textfsm: textfsm_templates/cl_showsys.tfsm

  linux:
    version: all
    command: cat /proc/uptime; hostnamectl
    textfsm: textfsm_templates/linux_showsys.tfsm

  sonic:
    version: all
    command: cat /proc/uptime; hostnamectl; show version
    textfsm: textfsm_templates/sonic_showsys.tfsm

  nxos:
    version: all
    command: "show version | json"
    normalize: '[
    "kickstart_ver_str: version",
    "manufacturer: vendor?Cisco|Cisco",
    "chassis_id: model",
    "os: os?|nxos",
    "kern_uptm_days: kern_uptm_days?|0",
    "kern_uptm_hrs: kern_uptm_hrs?|0",
    "kern_uptm_mins: kern_uptm_mins?|0",
    "kern_uptm_secs: kern_uptm_secs?|0",
    "cpu_name: architecture"
    ]'

  iosxr:
    version: all
    command: show version
    textfsm: textfsm_templates/cisco_xr_show_version.tfsm

  junos-qfx:
    version: all
    command:
      - command: "show system information | display json"
        normalize: 'system-information/*/[
        "hardware-model/[0]/data: model",
        "os-name/[0]/data: os",
        "os-version/[0]/data: version",
        "vendor: vendor?|Juniper"
        ]'
      - command: "show system uptime | display json"
        normalize: 'multi-routing-engine-results/[0]/multi-routing-engine-item/[0]/system-uptime-information/*/[
        "system-booted-time/[0]/time-length/[0]/attributes: bootupTimestamp?|"
        ]'

  junos-ex:
    copy: junos-qfx

  junos-mx:
    version: all
    command:
      - command: "show system information | display json"
        normalize: 'system-information/*/[
        "hardware-model/[0]/data: model",
        "os-name/[0]/data: os",
        "os-version/[0]/data: version",
        "vendor: vendor?|Juniper"
        ]'
      - command: "show system uptime | display json"
        normalize: 'system-uptime-information/*/[
        "system-booted-time/[0]/time-length/[0]/attributes: bootupTimestamp?|"
        ]'