service: fs
type: counters
keys:
  - mountPoint
ignore-fields:
  - usedSize
  - availSize
show-fields:
  - mountPoint
  - totalSize
  - usedSize
  - usedPercent
  - device
apply:
  cumulus:
    copy: linux

  linux:
    version: all
    command: df -hT
    textfsm: textfsm_templates/fs.tfsm

  sonic:
    copy: linux

  eos:
    version: all
    command: bash timeout 5 df -hT
    textfsm: textfsm_templates/fs.tfsm

  nxos:
    version: all
    command: run bash df -hT
    textfsm: textfsm_templates/fs.tfsm

  iosxr:
    version: all
    command: show filesystem location all
    textfsm: textfsm_templates/cisco_xr_show_filesystem.tfsm

  junos-qfx:
    version: all
    command: show system storage
    textfsm: textfsm_templates/fs.tfsm

  junos-ex:
    copy: junos-qfx

  junos-mx:
    copy: junos-qfx
