service: vlan
keys:
  - vlanName

show-fields:
  - vlanName
  - vlan
  - interfaces

apply:
  cumulus:
    version: all
    command: /sbin/bridge -c vlan show
    textfsm: textfsm_templates/linux_vlan.tfsm

  linux:
    copy: cumulus

  sonic:
    copy: cumulus

  eos:
    version: all
    command: show vlan brief
    normalize: 'vlans/*:vlan/[
    "interfaces/*: interfaces?|[]",
    "name: vlanName",
    "status: state",
    ]'

  nxos:
    version: all
    command: show vlan brief | json
    normalize: 'TABLE_vlanbriefxbrief/ROW_vlanbriefxbrief/*/[
    "vlanshowbr-vlanid: vlan",
    "vlanshowbr-vlanname: vlanName",
    "vlanshowbr-vlanstate: state",
    "vlanshowbr-shutstate: adminState",
    "vlanshowplist-ifidx: interfaces?|",
    ]'

  # ios-xr uses bridge-groups,

  junos-qfx:
    version: all
    command: show vlans detail | display json
    normalize: 'l2ng-l2ald-vlan-instance-information/l2ng-l2ald-vlan-instance-group/*/[
    "l2ng-l2rtb-vlan-tag/[0]/data: vlan",
    "l2ng-l2rtb-vlan-member/[*]/l2ng-l2rtb-vlan-member-interface/[0]/data: interfaces?|[]",
    "l2ng-l2rtb-vlan-name/[0]/data: vlanName",
    "l2ng-l2rtb-instance-state/[0]/data: state",
    ]'

  junos-ex:
    copy: junos-qfx
